-- db/seed.sql
USE drivncook;

-- Admin user
-- NOTE: Replace <HASH> with a password_hash(...) generated by PHP for the chosen password.
-- Example to generate a hash: php -r "echo password_hash('admin123', PASSWORD_DEFAULT)."\n;
INSERT INTO users (nom, email, mot_de_passe, role) VALUES ('Admin', 'admin@example.com', '<HASH>', 'admin');

-- Sample franchise user (also replace <HASH2> with a generated hash)
INSERT INTO users (nom, email, mot_de_passe, role) VALUES ('Franchise Test', 'fran1@example.com', '<HASH2>', 'franchise');

-- Create a franchise linked to the sample user (replace user_id if needed)
INSERT INTO franchises (user_id, ville, telephone, date_entree, chiffre_affaires) VALUES (2, 'Paris', '0123456789', '2025-01-01', 0.00);

-- Sample camions
INSERT INTO camions (numero_camion, etat, emplacement, franchise_id) VALUES ('CAM-001', 'actif', 'Paris', 1);
INSERT INTO camions (numero_camion, etat, emplacement, franchise_id) VALUES ('CAM-002', 'maintenance', 'Paris', 1);